#!/usr/bin/env ruby
$LOAD_PATH.unshift File.dirname(__FILE__) + '/../../../lib'
require 'rubygems'
require 'drb/drb'
require 'rbconfig'
require 'spec'

module Spec
  module Runner
    class RailsSpecServer
      def run(args, stderr, stdout)
        puts "Running ..."
        ::Dispatcher.reset_application!
        ::Dependencies.mechanism = :load
        require_dependency('application.rb') unless Object.const_defined?(:ApplicationController)
    
        $context_runner = OptionParser.create_context_runner(args, false, stderr, stdout)
        args.each do |file_or_dir|
          if File.directory?(file_or_dir)
            Dir["#{file_or_dir}/**/*.rb"].each do |file| 
              load file
            end
          else
            load file_or_dir
          end
        end
        $context_runner.run(false) unless args.empty?
        puts "Finished."
      end
    end
  end
end
puts "Loading Rails environment"

ENV["RAILS_ENV"] = "test"
require File.dirname(__FILE__) + '/../config/environment'
require 'dispatcher'

puts "Ready"
DRb.start_service("druby://localhost:8989", Spec::Runner::RailsSpecServer.new)
DRb.thread.join