#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts "=== ADD NEW ROLE ==="
print 'Role name: '
role_name = $stdin.gets.chomp
print 'Translated name: '
role_tr_name = $stdin.gets.chomp

roles = Role.find(:all)
role = roles.detect { |role| role.name == role_name or role.translate == role_tr_name }

unless role.nil?
  print "\n"
  puts "ERROR: Role named '#{role_name}' already exists!"
  exit
end

print 'Permissions, separated by a comma: '
perm_names = $stdin.gets.chomp.split(',').collect { |p| p.strip }

perms = Permission.find(:all)
if perms.empty? and !perm_names.empty?
  print "\n"
  puts 'No permissions. That can\'t be good.'
  exit
end

perms_to_add = []
perm_names.each do |perm_name|
  perm = perms.detect { |perm| perm.name == perm_name or perm.translate == perm_name }
  
  if perm.nil?
    print "\n"
    print "ERROR: Couldn't find permission named '#{perm_name}'"
    exit
  end
  
  perms_to_add.push(perm)
end

role = Role.new
role.name = role_name
role.save!
role.set(role_tr_name)

perms_to_add.each do |perm|
  role.set_permission(perm, 1)
end

print "\n"
puts "Created role named '#{role_name}'"