#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts "=== ADD NEW USER ==="
print 'New Login: '
login_name = $stdin.gets.chomp

unless User.find_by_login(login_name).nil?
  print "\n"
  puts "ERROR: User with that login already exists."
  exit
end

print 'New Password: '
password_val = $stdin.gets.chomp
print 'Confirm Password: '
unless $stdin.gets.chomp == password_val
  print "\n"
  puts "ERROR: Passwords did not match."
  exit
end

print 'Roles, more than one separated by a comma: '
role_names = $stdin.gets.chomp

roles = Role.find(:all)

roles_to_add = []
role_names.each do |role_name|
  role = roles.detect { |role| role.name == role_name or role.translate == role_name }
  
  if role.nil?
    print "\n"
    puts "ERROR: Couldn't find a role named '#{role_name}'"
    exit
  end
  
  roles_to_add.push(role)
end

newuser = User.new
newuser.login = login_name
newuser.password = password_val
newuser.save!

roles_to_add.each do |role|
  newuser.add_role(role)
end

print "\n"
puts "New user created."