#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts "=== DELETE ROLE ==="
print 'Role name: '
role_name = $stdin.gets.chomp

roles = Role.find(:all)
if roles.empty?
  print "\n"
  puts 'No roles.'
  exit
end

role = roles.detect { |role| role.name == role_name or role.translate == role_name }

if role.nil?
  print "\n"
  puts "ERROR: Couldn't find role named '#{role_name}'"
  exit
end

result = ''
while result != 'y' and result != 'n'
  print "Attempting to destroy '#{role_name}'! Are you sure (Y/N)? "
  result = $stdin.gets.chomp.downcase
end

if result == 'n'
  print "\n"
  puts 'Role was not deleted.'
  exit
end

role.destroy
print "\n"
puts "#{role_name} has been deleted."