#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts "=== REMOVE ROLE FROM USER ==="
print 'Login: '
login_name = $stdin.gets.chomp

if (user = User.find_by_login(login_name)).nil?
  print "\n"
  puts "ERROR: User with that login doesn't exist."
  exit
end

print 'Role(s), more than one separated by a comma: '
role_names = $stdin.gets.chomp

roles = Role.find(:all)

roles_to_remove = []
role_names.each do |role_name|
  role = roles.detect { |role| role.name == role_name or role.translate == role_name }
  
  if role.nil?
    print "\n"
    puts "ERROR: Couldn't find a role named '#{role_name}'"
    exit
  end
  
  roles_to_remove.push(role)
end

roles_to_remove.each do |role|
  begin
    user.remove_role(role)
  rescue UserDoesntHaveRoleException
  end
end

print "\n"
puts "Role(s) removed from user."