#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts '=== ACTIVATE A THEME IN RAILFROG ==='
if ARGV.empty?
  print 'Theme name: '
  theme_name = $stdin.gets.chomp
else
  theme_name = ARGV[0].to_s
end

puts "Attempting to make '#{theme_name}' the active theme..."

make_active_theme = nil
Dir.foreach(Theme::get_path) do |theme|
  next unless theme == theme_name
  next unless File.exists?(Theme::get_path + '/' + theme + '/theme.yml')
  
  yaml = YAML::load(File.open(Theme::get_path + '/' + theme + '/theme.yml', 'r'))
  yaml['id'] = theme
  yaml['active'] = Theme::current == theme
  make_active_theme = yaml
end

if make_active_theme.nil?
  print "\n"
  puts "ERROR: Theme with that name doesn't exist!"
  exit
elsif Option.get('default_theme') == theme_name
  print "\n"
  puts "ERROR: #{theme_name} is already the active theme."
  exit
end

Option.set('default_theme', theme_name)

print "\n"
puts "#{theme_name} is now the active theme!"