#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts "=== ADD PERMISSION TO ROLE ==="
print 'Role name: '
role_name = $stdin.gets.chomp

roles = Role.find(:all)
if roles.empty?
  print "\n"
  puts 'No roles.'
  exit
end

role = roles.detect { |role| role.name == role_name or role.translate == role_name }

if role.nil?
  print "\n"
  puts "ERROR: Couldn't find role named '#{role_name}'"
  exit
end

print 'Permissions to add, more than one separated by a comma: '
perm_names = $stdin.gets.chomp.split(',').collect { |p| p.strip }

if perm_names.empty?
  print "\n"
  puts "No permissions were changed."
  exit
end

perms = Permission.find(:all)
if perms.empty? and !perm_names.empty?
  print "\n"
  puts 'No permissions. That can\'t be good.'
  exit
end

perms_to_add = []
perm_names.each do |perm_name|
  perm = perms.detect { |perm| perm.name == perm_name or perm.translate == perm_name }
  
  if perm.nil?
    print "\n"
    print "ERROR: Couldn't find permission named '#{perm_name}'"
    exit
  end
  
  perms_to_add.push(perm)
end

perms_to_add.each do |perm|
  role.set_permission(perm, 1)
end

print "\n"
puts "Permission(s) given to #{role_name}."