#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts "=== CHECK ROLE PERMISSION ==="
print 'Role name: '
role_name = $stdin.gets.chomp

roles = Role.find(:all)
if roles.empty?
  print "\n"
  puts 'No roles.'
  exit
end

role = roles.detect { |role| role.name == role_name or role.translate == role_name }

if role.nil?
  print "\n"
  puts "ERROR: Couldn't find role named '#{role_name}'"
  exit
end

print 'Permission name: '
perm_name = $stdin.gets.chomp

perms = Permission.find(:all)
if perms.empty?
  print "\n"
  puts 'No permissions. That can\'t be good.'
  exit
end

perm = perms.detect { |perm| perm.name == perm_name or perm.translate == perm_name }

if perm.nil?
  print "\n"
  print "ERROR: Couldn't find permission named '#{perm_name}'"
  exit
end

result = ''
while result != 'y' and result != 'n'
  print "Check parent role permissions too (Y/N)? "
  result = $stdin.gets.chomp.downcase
end

check_parents = result == 'n' ? true : false

puts 'Checking...'
if role.has_permission?(perm, check_parents)
  print "\n"
  puts "#{role_name} HAS PERMISSION TO #{perm_name}"
else
  print "\n"
  puts "#{role_name} DOES NOT HAVE PERMISSION TO #{perm_name}"
end