#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts '=== DELETE A TEMPLATE FOR A THEME IN RAILFROG ==='
print 'Theme name: '
theme_name = $stdin.gets.chomp

the_theme = nil
Dir.foreach(Theme::get_path) do |theme|
  next unless theme == theme_name
  next unless File.exists?(Theme::get_path + '/' + theme + '/theme.yml')
  
  yaml = YAML::load(File.open(Theme::get_path + '/' + theme + '/theme.yml', 'r'))
  yaml['id'] = theme
  yaml['active'] = Theme::current == theme
  the_theme = yaml
end

if the_theme.nil?
  print "\n"
  puts "ERROR: Theme with that name doesn't exist!"
  exit
end

print 'Template name (without the .rhtml extension): '
template_name = $stdin.gets.chomp

template_path = Theme::get_path + '/' + theme_name + '/templates/' + template_name + '.rhtml'
unless File.exists?(template_path)
  print "\n"
  puts "ERROR: Template with that name doesn't exist!"
  exit
end

result = ''
while result != 'y' and result != 'n'
  print "Attempting to destroy '#{template_name}'! Are you sure (Y/N)? "
  result = $stdin.gets.chomp.downcase
end

if result == 'n'
  print "\n"
  puts 'Template was not deleted.'
  exit
elsif File.delete(template_path) == 0
  print "\n"
  puts "ERROR: Failed to delete template."
  exit
end

print "\n"
puts "#{template_name} deleted from #{theme_name}."