#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts '=== DELETE AN ITEM FROM RAILFROG ==='
if ARGV.empty?
  print 'Item name: '
  item_name = $stdin.gets.chomp
else
  item_name = ARGV[0].to_s
end

if (item = Item.find_by_name(item_name)).nil?
  print "\n"
  puts "ERROR: Item named '#{item_name}' doesn't exist!"
  exit
end

result = ''
while result != 'y' and result != 'n'
  print "Attempting to destroy '#{item_name}'! Are you sure (Y/N)? "
  result = $stdin.gets.chomp.downcase
end

if result == 'n'
  print "\n"
  puts 'Item was not deleted.'
  exit
end

item.destroy
print "\n"
puts 'Item destroyed.'