#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts '=== Listing All Permissions By Role Name ==='
puts 'Role'.ljust(20) + 'Permission'.ljust(30) + 'Permission Internal Name'

perms = Permission.find(:all)
if perms.empty?
  print "\n"
  puts 'No permissions. That can\'t be good.'
  exit
end

roles = Role.find(:all)
if roles.empty?
  print "\n"
  puts 'No roles.'
  exit
end

roles.each do |role|
  perms.each do |perm|
    puts role.translate.ljust(20) + perm.translate.ljust(30) + perm.name if role.has_permission?(perm, true)
  end
end