#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts '=== Listing All Items ==='
puts 'Name'.ljust(15) + 'Content Type'.ljust(20) + 'Content Extensions (if any)'

items = Item.find(:all, :include => [:extension, :item_extensions], :order => 'items.name ASC')
if items.empty?
  print "\n"
  puts 'No items. Create one with the create_item script.'
  exit
end

items.each do |item|
  item_exts = []
  item.item_extensions.each do |ext|
    item_exts.push(ext.extension.name)
  end
  item_exts = item_exts.join(',')
  puts item.name.ljust(15) + item.extension.name.ljust(20) + item_exts
end