#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts '=== Listing All Roles ==='
puts 'Name'.ljust(30) + 'Internal Name'

roles = Role.find(:all)
if roles.empty?
  print "\n"
  puts 'No roles.'
  exit
end

roles.each do |role|
  puts role.translate.ljust(30) + role.name
end