#!/usr/bin/env ruby

print 'Loading railfrog system...'
require 'config/environment'
puts 'Done'

print "\n"
puts '=== UNINSTALL AN EXTENSION IN RAILFROG ==='
print 'Extension name: '
ext_name = $stdin.gets.chomp

unless Extension.exists?(ext_name)
  print "\n"
  puts "ERROR: #{ext_name} hasn't been installed yet."
  exit
end

result = ''
while result != 'y' and result != 'n'
  print "Attempting to uninstall '#{ext_name}'! Are you sure (Y/N)? "
  result = $stdin.gets.chomp.downcase
end

if result == 'n'
  print "\n"
  puts 'Extension was not uninstalled.'
  exit
end

items = Item.find(:all)
items.each do |item| 
  if item.has_extension?(ext_name)
    print "\n"
    puts "ERROR: Some items have this extension. You must remove all those items first."
    puts "Extension was not uninstalled."
    exit
  end
end

begin
  extension = Extension.find_by_name(ext_name)
  extension.ext_cmd_uninstall(extension)
rescue NoMethodError
end
Extension.uninstall(ext_name)

print "\n"
puts "#{ext_name} has been uninstalled."